apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.service | lower | quote }}
  labels:
    {{- include "bitcoin.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ .Values.service | lower | quote }}
      version: {{ .Values.version | quote }}
