{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.service | lower | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.service | lower | quote }}
    app.kubernetes.io/part-of: {{ .Values.system | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  gateways:
    - {{ .Values.istio.ingressGateway.name | quote }} 
  hosts:
    - {{ .Values.istio.ingressGateway.host | quote }}
  http:
{{- range .Values.ports }}
    - match:
      - port: {{ .port }}
{{- range $.Values.istio.ingressGateway.matchPrefix }}
      - uri:
          prefix: {{ . | quote }}
{{- end }}
      route:
      - destination:
          host: {{ (print $.Values.service "." $.Release.Namespace ".svc.cluster.local")  | quote }}
          subset: {{ (print "v" $.Values.version) | quote }}
          port:
            number: {{ .port }}
      corsPolicy:
{{- toYaml $.Values.istio.corsPolicy | nindent 8 }}
{{- if $.Values.istio.retries }}
      retries:
{{ toYaml $.Values.istio.retries | indent 8 }}
      timeout: {{ required "You must specify an overall timeout to use retries" $.Values.istio.overallTimeout}}
{{- else if $.Values.istio.overallTimeout }}
      timeout: {{ $.Values.istio.overallTimeout }}
{{- end }}
{{- end }}
{{- end }}
