{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.service | lower | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.service | lower | quote }}
    app.kubernetes.io/part-of: {{ .Values.system | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  gateways:
    - {{ .Values.istio.ingressGateway.name | quote }} 
  hosts:
    - {{ .Values.istio.ingressGateway.host | quote }}
  http:
    - match:
{{- range .Values.istio.ingressGateway.matchPrefix }}
      - uri:
          prefix: {{ . | quote }}
{{- end }}
      route:
      - destination:
          host: {{ (print .Values.service "." .Release.Namespace ".svc.cluster.local")  | quote }}
          subset: {{ (print "v" .Values.version) | quote }}
      corsPolicy:
        allowOrigins:
          - regex: ".*"
        allowMethods:
          - POST
          - GET
          - OPTIONS
          - PUT
          - DELETE
        allowHeaders:
          - grpc-timeout
          - content-type
          - keep-alive
          - user-agent
          - cache-control
          - content-type
          - content-transfer-encoding
          - custom-header-1
          - x-accept-content-transfer-encoding
          - x-accept-response-streaming
          - x-grpc-web
          - x-user-agent
        maxAge: 1728s
        exposeHeaders:
          - grpc-timeout
          - content-type
          - keep-alive
          - user-agent
          - cache-control
          - content-type
          - content-transfer-encoding
          - custom-header-1
          - x-accept-content-transfer-encoding
          - x-accept-response-streaming
          - x-grpc-web
          - x-user-agent
{{- if .Values.istio.retries }}
      retries:
{{ toYaml .Values.istio.retries | indent 8 }}
      timeout: {{ required "You must specify an overall timeout to use retries" .Values.istio.overallTimeout}}
{{- else if .Values.istio.overallTimeout }}
      timeout: {{ .Values.istio.overallTimeout }}
{{- end }}
{{- end }}
