apiVersion: v2
appVersion: "23"
kubeVersion: ">=1.23.0-0"
version: 0.1.3

name: bitcoin-node
description: A Helm chart for running a Bitcoin node.

home: https://apparatus.live
icon: https://apparatus.live/wp-content/uploads/2024/03/cropped-Circle_Original-1.png
sources:
  - https://github.com/Topl/helm-charts
  - https://topl.github.io/helm-charts
keywords:
  - apparatus
  - bitcoin
  - blockchain
maintainers:
  - name: apparatus
    url: https://github.com/Topl
