apiVersion: v2
name: bifrost-consensus-testnet
description: Launches a private testnet using configurable nodes and artificial throttling.

type: application

version: 0.1.0

appVersion: "2.0.0-alpha1"

##TODO: Find a better icon.
icon: https://uploads-ssl.webflow.com/60f98f46d44e675abb7e66ea/611c4d83ed3df101fd221875_topl_basew.svg

## These settings control where the results are published
#results:
  ## The Storage Bucket on Google Cloud
  #bucket: bifrost-topl-labs-testnet-scenario-results
  ## The prefix to apply to each uploaded file.  The scenario name is automatically applied as a suffix to this prefix.
  #prefix: /simulation/results/

## These settings control the parameters of the scenario
#scenario:
  ## The height that must be reached by each node in the scenario
  #targetHeight: 30
  ## The number of transactions to generate and broadcast per second.  Transactions are broadcasted to nodes at random.
  #transactionsPerSecond: 2.5
  ## The maximum length of time to wait for an individual node to reach the target height.  If a node fails to reach
  ## the target height within this time, the scenario will still pass, but a log message will be presented
  ## indicating that it was terminated early.
  #timeout: 10 minutes

## These settings will apply to the configurations of all nodes.
#shared-config:
  ## Define custom application.conf overrides
  #bifrost:
    #big-bang:
      #staker-count: 2
    #protocols:
      #0:
        #slot-duration: 250 milli

## Define an entry for each node you wish to launch in the cluster
#configs:
  ## Name the node
  #producer0:
    ## Define custom application.conf overrides
    #bifrost:
      #big-bang:
        #local-staker-index: 0
    ## Define the network topology of this node
    #topology:
      ## Applies to all connections received by this node
      #ingress:
        ## The amount of throttling to impose on the local node's portion of the connection
        #throttle:
          #latency: 10 milli
          #downloadBytesPerSecond: 500000
          #uploadBytesPerSecond: 500000
  #producer1:
    #bifrost:
      #big-bang:
        #local-staker-index: 1
    #topology:
      #ingress:
        #throttle:
          #latency: 10 milli
          #downloadBytesPerSecond: 500000
          #uploadBytesPerSecond: 500000
  #relay0:
    #bifrost:
      #big-bang:
        #local-staker-index: -1
    #topology:
      #ingress:
        #throttle:
          #latency: 10 milli
          #downloadBytesPerSecond: 500000
          #uploadBytesPerSecond: 500000
      ## Outbound connections are defined here
      #egress:
          ## The name of the peer
        #- peer: producer0
          ## The amount of throttling to impose on the local node's portion of the connection
          #throttle:
            #latency: 10 milli
            #downloadBytesPerSecond: 500000
            #uploadBytesPerSecond: 500000
        #- peer: producer1
          #throttle:
            #latency: 10 milli
            #downloadBytesPerSecond: 500000
            #uploadBytesPerSecond: 500000
