apiVersion: v2
name: bifrost-consensus-testnet
description: Launches a private testnet using configurable nodes and artificial throttling.

type: application

version: 0.1.3

appVersion: "dev"

icon: https://topl.co/wp-content/uploads/2023/06/topl_white_horiz.svg
