apiVersion: v2
name: bifrost-consensus-testnet
description: Launches a private testnet using configurable nodes and artificial throttling.

type: application

version: 0.1.2

appVersion: "2.0.0-alpha1"

##TODO: Find a better icon.
icon: https://uploads-ssl.webflow.com/60f98f46d44e675abb7e66ea/611c4d83ed3df101fd221875_topl_basew.svg
