{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.service | lower | quote }}
  labels:
    {{- include "annulus.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "annulus.selectorLabels" . | nindent 6 }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "annulus.selectorLabels" . | nindent 10 }}
    ports:
{{- range .Values.ports }}
    - port: {{ .name | quote }}
      protocol: TCP
{{- end }}
  policyTypes:
  - Ingress
{{- end }}
