{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.redis.name }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
            {{- include "vertx.labels" . | nindent 12 }}
    ports:
    - port: "redis-port"
      protocol: TCP
  policyTypes:
  - Ingress
{{- end }}
