{{- if .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "genus.fullname" . }}
  labels:
    {{- include "genus.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
data:
  {{ .Values.configMap.fileName | default "config.yaml" }}: |-
{{ .Values.configMap.content | indent 4 }}
{{- end }}
