apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.service | lower | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.service | lower | quote }}
    app.kubernetes.io/part-of: {{ .Values.system | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  serviceName: {{ .Values.service | lower | quote }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service | lower | quote }}
      version: {{ .Values.version | quote }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        # Kubernetes recommended labels
        app.kubernetes.io/name: {{ .Values.service | lower | quote }}
        app.kubernetes.io/part-of: {{ .Values.system | quote }}
        app.kubernetes.io/version: {{ .Values.version | quote }}
        # Isio required labels
        app: {{ .Values.service | lower | quote }}
        version: {{ .Values.version | quote }}
    spec:
      nodeSelector: 
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      serviceAccountName: {{ .Values.serviceAccount.name | lower | quote }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.service | lower | quote }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy | quote }}
          env:
            - name: ORIENT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.service | lower | quote }}-db-password
                  key: db-password
           {{- toYaml .Values.env | nindent 10 }}
          args:
            - "--orientDbPassword"
            - "$(ORIENT_DB_PASSWORD)"
            - "--dataDir"
            - "/genus"
            - "--enableReplicator"
            - "{{ .Values.replicator.enable }}"
            - "--nodeRpcHost"
            - "{{ .Values.nodeRpc.host }}"
            - "--nodeRpcPort"
            - "{{ .Values.nodeRpc.port }}"
            - "--nodeRpcTls"
            - "{{ .Values.nodeRpc.tls }}"
          ports:
{{- range .Values.ports }}
            - name: {{ .name | quote }}
              containerPort: {{ .targetPort }}
              protocol: TCP
{{- end }}
{{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
{{- if .Values.probes }}
{{ toYaml .Values.probes | indent 10 }}
{{- end }}
          volumeMounts:
            - name: {{ (print .Values.service "-pv") | quote }}
              mountPath: "/genus"
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: {{ (print .Values.service "-pv") | quote }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.volume.storageClass }}
        resources:
          requests:
            storage: {{ .Values.volume.storageSize }}
