apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "genus.fullname" . }}
  labels:
    {{- include "genus.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "genus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- if .Values.configMap }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "genus.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "genus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MONGODB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongoDBSecretName | lower | quote }}
                  key: {{ .Values.mongoDBSecretData | lower | quote }}
          command:
          {{- range .Values.command }}
            - {{ . }}
          {{- end }}
          args:
          {{- range .Values.args }}
            - {{ . }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.grpcPort }}
              protocol: TCP
          {{- if .Values.probes }}
          {{ toYaml .Values.probes | indent 10 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.configMap }}
          volumeMounts:
            - name: {{ (print (include "genus.fullname" .) "-config") | quote }}
              mountPath: {{ .Values.configMap.mountPath | quote }}
      volumes:
        - name: {{ (print (include "genus.fullname" .) "-config") | quote }}
          configMap:
            name: {{ include "genus.fullname" . | lower | quote }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
