{{- if and (.Values.istio.enabled) (.Values.istio.createGrpcWebFilter) }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ .Values.service | lower | quote }}
  labels:
    {{- include "genus.labels" . | nindent 4 }}
spec:
  workloadSelector:
    labels:
      app: {{ .Values.service | lower | quote }}
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: "envoy.grpc_web"
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb"
{{- end }}
