{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "genus.fullname" . }}
  labels:
    {{- include "genus.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "genus.labels" . | nindent 4 }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
            {{- include "genus.labels" . | nindent 4 }}
    ports:
    - port: http
      protocol: TCP
    - port: grpc
      protocol: TCP
  policyTypes:
  - Ingress
{{- end }}
