apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.service | lower | quote }}
  labels:
    {{- include "genus.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "genus.selectorLabels" . | nindent 6 }}
