apiVersion: v1
kind: Service
metadata:
  name: {{ include "genus.fullname" . }}
  labels:
    {{- include "genus.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "genus.selectorLabels" . | nindent 4 }}
