apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service | lower | quote }}
  labels:
    {{- include "genus.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: {{ .Values.serviceType | quote }}
  ports:
{{- range .Values.ports }}
    - name: {{ .name | quote }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
{{- end }}
  selector:
    app: {{ .Values.service | lower | quote }}
