{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.service | lower | quote }}
  labels:
    {{- include "genus.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  gateways:
    - {{ .Values.istio.ingressGateway.name | quote }}
  hosts:
  {{- range .Values.istio.ingressGateway.hosts }}
    - {{ . | quote }}
  {{- end }}
  http:
  {{- range .Values.istio.virtualServiceRoutes.http }}
    - match:
      - port: {{ .port }}
      {{- range .matchPrefix }}
      - uri:
          prefix: {{ . | quote }}
      {{- end }}
      route:
      - destination:
          host: {{ (print $.Values.service "." $.Release.Namespace ".svc.cluster.local")  | quote }}
          port:
            number: {{ .targetPort }}
      corsPolicy:
      {{- toYaml $.Values.istio.corsPolicy | nindent 8 }}
      {{- if $.Values.istio.retries }}
      retries:
      {{ toYaml $.Values.istio.retries | nindent 8 }}
      timeout: {{ required "You must specify an overall timeout to use retries" $.Values.istio.overallTimeout}}
      {{- else if $.Values.istio.overallTimeout }}
      timeout: {{ $.Values.istio.overallTimeout }}
      {{- end }}
  {{- end }}
  tcp:
  {{- range .Values.istio.virtualServiceRoutes.tcp }}
    - match:
      - port: {{ .port }}
      route:
      - destination:
          host: {{ (print $.Values.service "." $.Release.Namespace ".svc.cluster.local")  | quote }}
          port:
            number: {{ .targetPort }}
      {{- if $.Values.istio.retries }}
      retries:
      {{ toYaml $.Values.istio.retries | nindent 8 }}
      timeout: {{ required "You must specify an overall timeout to use retries" $.Values.istio.overallTimeout}}
      {{- else if $.Values.istio.overallTimeout }}
      timeout: {{ $.Values.istio.overallTimeout }}
      {{- end }}
  {{- end }}
{{- end }}
