{{- if .Values.ingress.api.enabled -}}
{{- $fullName := include "annulus-api.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "annulus-api.labels" . | nindent 4 }}
  {{- with .Values.ingress.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.api.tls }}
  tls:
    {{- range .Values.ingress.api.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  defaultBackend:
    service: 
      name: {{ .Values.ingress.api.defaultBackend.serviceName }}
      port:
        number: {{ .Values.ingress.api.defaultBackend.port }}
  rules:
    - http:
        paths:
          {{- range .Values.ingress.api.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePort }}
          {{- end }}
{{- end }}