# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: bifrost-daml-broker

damlEnv: damlhub # possible values: dalmhub, cluster

toplEnv: valhalla # possible values: valhalla, cluster

damlDamlHubEnvConfig:
  ledgerId: w85m150i4gbsvl9m
  damlPort: "443"
  damlSecure: "true"

damlClusterEnvConfig:
  damlHost: canton-and-topl-service
  damlPort: "5011"
  damlSecure: "true"

toplValhallaNetworkConfig:
  network: valhalla
  bifrostUrl: https://vertx.topl.services/valhalla/63ed2dbf5ef2c40011c59cf2

toplClusterNetworkConfig:
  network: private
  bifrostUrl: http://localhost:9085

resources:
  limits:
    cpu: "2"
    memory: "1024Mi"

image:
  name: toplprotocol/bifrost-daml-broker
  tag:

replicaCount: 1

securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
