{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels: 
    {{- include "vertx.labels" . | nindent 4 }}
data:
    {{- if .Values.configMap.configMapProperties }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.configMap.configMapProperties "context" $ ) | nindent 2 }}
    {{- end }}
{{- end }}