{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels: 
    {{- include "vertx.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.configMap.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}