{{- if .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service | lower | quote }}
  labels:
    {{- include "faucet.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
data:
  {{ .Values.configMap.fileName | default "config.yaml" }}: |-
    {{ .Values.configMap.content | nindent 4 }}
{{- end }}
