apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.service | lower | quote }}
  labels:
    {{- include "faucet.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  host: {{ (print .Values.service "." .Release.Namespace ".svc.cluster.local")  | quote }}
  {{- if .Values.outlierDetection }}
  trafficPolicy:
    outlierDetection:
      {{ toYaml .Values.outlierDetection | nindent 6 }}
  {{- end }}
  subsets:
    - name: {{ (print "v" .Values.version) | quote }}
      labels:
        version: {{ .Values.version | quote }}
