apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.service | lower | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.service | lower | quote }}
    app.kubernetes.io/part-of: {{ .Values.system | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  host: {{ (print .Values.service "." .Release.Namespace ".svc.cluster.local")  | quote }}
{{- if .Values.outlierDetection }}
  trafficPolicy:
    outlierDetection:
{{ toYaml .Values.outlierDetection | indent 6 }}
{{- end }}
  subsets:
    - name: {{ (print "v" .Values.version) | quote }}
      labels:
        version: {{ .Values.version | quote }}
