{{- if .Values.bridgeUi.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "btc-bridge.ui.serviceAccountName" . }}
  labels:
    {{- include "btc-bridge.ui.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.bridgeUi.serviceAccount.automountToken }}
{{- end }}
