# a config map for the broker
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bifrost.daml.broker.config.name" . }}
data:
  {{ include "bifrost.daml.broker.daml.settings" . | nindent 2 }}
  {{ include "bifrost.daml.broker.topl.settings" . | nindent 2 }}