apiVersion: v2
appVersion: "latest"
kubeVersion: ">=1.23.0-0"
version: 0.1.3

name: btc-bridge
description: Helm Chart for deploying the Apparatus BTC Bridge.

home: https://apparatus.live
icon: https://apparatus.live/wp-content/uploads/2024/03/cropped-Circle_Original-1.png
sources:
  - https://github.com/Topl/helm-charts
  - https://topl.github.io/helm-charts
keywords:
  - apparatus
  - bridge
  - blockchain
maintainers:
  - name: apparatus
    url: https://github.com/Topl
